#!/usr/bin/env zsh
if [[ -z $STOW_FOLDERS ]]; then
 STOW_FOLDERS="bash,fzf,martin,lazygit,lvim,nvim,tmux,oh-my-zsh,p10k,zsh"
fi

if [[ -z $DOTFILES ]]; then
  DOTFILES=$HOME/.dotfiles
fi

STOW_FOLDERS=$STOW_FOLDERS DOTFILES=$DOTFILES $DOTFILES/install
# STOW_FOLDERS=$STOW_FOLDERS DOTFILES=$DOTFILES $DOTFILES/clean-env
