"$schema" = 'https://starship.rs/config-schema.json'

format = """
$username\
$hostname\
$directory\
$git_branch\
$git_state\
$git_status\
$docker_context\
$rust\
$nodejs\
$bun\
$lua\
$python\
$fill\
$cmd_duration\
$os\
$time\
$line_break\
$character
"""

[character]
success_symbol = '[](bold green)'
error_symbol = '[](bold red)'
vimcmd_symbol = '[](bold green)'
vimcmd_replace_one_symbol = '[](bold purple)'
vimcmd_replace_symbol = '[](bold purple)'
vimcmd_visual_symbol = '[](bold yellow)'
disabled = false

[time]
disabled = false
format = '[$time]($style) '
style = 'white'

[line_break]
disabled = false

[cmd_duration]
format = '[$duration]($style) '
style = 'white'

[directory]
read_only = " 󰌾"

[docker_context]
symbol = " "

[git_branch]
symbol = " "
format = '[](black)[$symbol$branch(:$remote_branch)]($style)[](black) '
style = 'bg:black fg:white'

[git_commit]
tag_symbol = '  '

[hostname]
ssh_symbol = " "

[lua]
symbol = " "

[nodejs]
symbol = "[⬢](bold green) "

[os]
disabled = false
format = '[$symbol]($style) '
style = 'white'

[os.symbols]
Arch = " "
Macos = " "
Pop = " "
Ubuntu = " "
Unknown = " "

[package]
symbol = "󰏗 "

[bun]
symbol = " "
format = "[${symbol}]($style) "
style = 'white'

[python]
symbol = " "
format = "[${symbol}$virtualenv]($style) "
style = "yellow"

[rust]
symbol = "󱘗 "
format = "[${symbol}]($style) "
style = 'fg:#d65d0e'
